### ISSUE TITLE
先赞一个

### ISSUE THREAD

**Issue by ForrestAlfred** [hades0918/CheckLeak#3]
赞一下, 帮我检测了几个以前写的代码里没做内存处理的部分.
但是现在我用了ReactiveCocoa 的'@Weakify' 和 '@Strongify' , 所以现在这种检测方式貌似就不适用了.

**Comment by hades0918** [comment]
这种还检测不了

**Comment by ForrestAlfred** [comment]
恩,我建议可以检测一下block 里面又没有第一个写@Strongify,不知道这样能不能实现.

**Comment by ForrestAlfred** [comment]
好像目前还真不能简单地用字符串匹配来做这个...因为我一个block 里可能有多层Block,而这种情况我只在第一层的block 里写@Strongify.
